# This file will be regenerated by `mulle-sourcetree-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/Files.cmake
#
# Disable generation of this file with:
#
# mulle-sde environment set MULLE_SOURCETREE_TO_CMAKE_DEPENDENCIES_FILE DISABLE
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# Generated from sourcetree: 6a1a8ae7-8c93-4908-ae06-722cd7143197;mulle-objc-runtime;no-import,no-header,no-singlephase;
# Disable with : `mulle-sourcetree mark mulle-objc-runtime no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-objc-runtime no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-objc-runtime no-cmake-sdk-<name>`
#
if( NOT MULLE__OBJC__RUNTIME_LIBRARY)
   find_library( MULLE__OBJC__RUNTIME_LIBRARY NAMES
      ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-objc-runtime${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
      ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-objc-runtime${CMAKE_STATIC_LIBRARY_SUFFIX}
      mulle-objc-runtime
      NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH
   )
   if( NOT MULLE__OBJC__RUNTIME_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
      find_library( MULLE__OBJC__RUNTIME_LIBRARY NAMES
         ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-objc-runtime${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
         ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-objc-runtime${CMAKE_STATIC_LIBRARY_SUFFIX}
         mulle-objc-runtime
      )
   endif()
   message( STATUS "MULLE__OBJC__RUNTIME_LIBRARY is ${MULLE__OBJC__RUNTIME_LIBRARY}")
   #
   # The order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need.
   #
   if( MULLE__OBJC__RUNTIME_LIBRARY)
      #
      # Add MULLE__OBJC__RUNTIME_LIBRARY to ALL_LOAD_DEPENDENCY_LIBRARIES list.
      # Disable with: `mulle-sourcetree mark mulle-objc-runtime no-cmake-add`
      #
      list( APPEND ALL_LOAD_DEPENDENCY_LIBRARIES ${MULLE__OBJC__RUNTIME_LIBRARY})
      #
      # Inherit information from dependency.
      # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
      # Disable with: `mulle-sourcetree mark mulle-objc-runtime no-cmake-inherit`
      #
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLE__OBJC__RUNTIME_ROOT "${MULLE__OBJC__RUNTIME_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLE__OBJC__RUNTIME_ROOT "${_TMP_MULLE__OBJC__RUNTIME_ROOT}" DIRECTORY)
      #
      #
      # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark mulle-objc-runtime no-cmake-dependency`
      #
      foreach( _TMP_MULLE__OBJC__RUNTIME_NAME "mulle-objc-runtime")
         set( _TMP_MULLE__OBJC__RUNTIME_DIR "${_TMP_MULLE__OBJC__RUNTIME_ROOT}/include/${_TMP_MULLE__OBJC__RUNTIME_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( IS_DIRECTORY "${_TMP_MULLE__OBJC__RUNTIME_DIR}")
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE__OBJC__RUNTIME_DIR}")
            #
            include( "${_TMP_MULLE__OBJC__RUNTIME_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE__OBJC__RUNTIME_DIR}")
            #
            unset( MULLE__OBJC__RUNTIME_DEFINITIONS)
            include( "${_TMP_MULLE__OBJC__RUNTIME_DIR}/Definitions.cmake" OPTIONAL)
            list( APPEND INHERITED_DEFINITIONS ${MULLE__OBJC__RUNTIME_DEFINITIONS})
            break()
         else()
            message( STATUS "${_TMP_MULLE__OBJC__RUNTIME_DIR} not found")
         endif()
      endforeach()
      #
      # Search for "MulleObjCLoader+<name>.h" in include directory.
      # Disable with: `mulle-sourcetree mark mulle-objc-runtime no-cmake-loader`
      #
      if( NOT NO_INHERIT_OBJC_LOADERS)
         foreach( _TMP_MULLE__OBJC__RUNTIME_NAME "mulle-objc-runtime")
            set( _TMP_MULLE__OBJC__RUNTIME_FILE "${_TMP_MULLE__OBJC__RUNTIME_ROOT}/include/${_TMP_MULLE__OBJC__RUNTIME_NAME}/MulleObjCLoader+${_TMP_MULLE__OBJC__RUNTIME_NAME}.h")
            if( EXISTS "${_TMP_MULLE__OBJC__RUNTIME_FILE}")
               list( APPEND INHERITED_OBJC_LOADERS ${_TMP_MULLE__OBJC__RUNTIME_FILE})
               break()
            endif()
         endforeach()
      endif()
   else()
      # Disable with: `mulle-sourcetree mark mulle-objc-runtime no-require-link`
      message( SEND_ERROR "MULLE__OBJC__RUNTIME_LIBRARY was not found")
   endif()
endif()


#
# Generated from sourcetree: 5B278807-A894-4D62-904A-7AF69B5286C2;mulle-objc-debug;no-all-load,no-cmake-loader,no-cmake-searchpath,no-import,no-require,no-singlephase;
# Disable with : `mulle-sourcetree mark mulle-objc-debug no-link`
# Disable for this platform: `mulle-sourcetree mark mulle-objc-debug no-cmake-platform-${MULLE_UNAME}`
# Disable for a sdk: `mulle-sourcetree mark mulle-objc-debug no-cmake-sdk-<name>`
#
if( NOT MULLE__OBJC__DEBUG_LIBRARY)
   find_library( MULLE__OBJC__DEBUG_LIBRARY NAMES
      ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-objc-debug${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
      ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-objc-debug${CMAKE_STATIC_LIBRARY_SUFFIX}
      mulle-objc-debug
      NO_CMAKE_SYSTEM_PATH NO_SYSTEM_ENVIRONMENT_PATH
   )
   if( NOT MULLE__OBJC__DEBUG_LIBRARY AND NOT DEPENDENCY_IGNORE_SYSTEM_LIBARIES)
      find_library( MULLE__OBJC__DEBUG_LIBRARY NAMES
         ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-objc-debug${CMAKE_DEBUG_POSTFIX}${CMAKE_STATIC_LIBRARY_SUFFIX}
         ${CMAKE_STATIC_LIBRARY_PREFIX}mulle-objc-debug${CMAKE_STATIC_LIBRARY_SUFFIX}
         mulle-objc-debug
      )
   endif()
   message( STATUS "MULLE__OBJC__DEBUG_LIBRARY is ${MULLE__OBJC__DEBUG_LIBRARY}")
   #
   # The order looks ascending, but due to the way this file is read
   # it ends up being descending, which is what we need.
   #
   if( MULLE__OBJC__DEBUG_LIBRARY)
      #
      # Add MULLE__OBJC__DEBUG_LIBRARY to DEPENDENCY_LIBRARIES list.
      # Disable with: `mulle-sourcetree mark mulle-objc-debug no-cmake-add`
      #
      list( APPEND DEPENDENCY_LIBRARIES ${MULLE__OBJC__DEBUG_LIBRARY})
      #
      # Inherit information from dependency.
      # Encompasses: no-cmake-searchpath,no-cmake-dependency,no-cmake-loader
      # Disable with: `mulle-sourcetree mark mulle-objc-debug no-cmake-inherit`
      #
      # temporarily expand CMAKE_MODULE_PATH
      get_filename_component( _TMP_MULLE__OBJC__DEBUG_ROOT "${MULLE__OBJC__DEBUG_LIBRARY}" DIRECTORY)
      get_filename_component( _TMP_MULLE__OBJC__DEBUG_ROOT "${_TMP_MULLE__OBJC__DEBUG_ROOT}" DIRECTORY)
      #
      #
      # Search for "Definitions.cmake" and "DependenciesAndLibraries.cmake" to include.
      # Disable with: `mulle-sourcetree mark mulle-objc-debug no-cmake-dependency`
      #
      foreach( _TMP_MULLE__OBJC__DEBUG_NAME "mulle-objc-debug")
         set( _TMP_MULLE__OBJC__DEBUG_DIR "${_TMP_MULLE__OBJC__DEBUG_ROOT}/include/${_TMP_MULLE__OBJC__DEBUG_NAME}/cmake")
         # use explicit path to avoid "surprises"
         if( IS_DIRECTORY "${_TMP_MULLE__OBJC__DEBUG_DIR}")
            list( INSERT CMAKE_MODULE_PATH 0 "${_TMP_MULLE__OBJC__DEBUG_DIR}")
            #
            include( "${_TMP_MULLE__OBJC__DEBUG_DIR}/DependenciesAndLibraries.cmake" OPTIONAL)
            #
            list( REMOVE_ITEM CMAKE_MODULE_PATH "${_TMP_MULLE__OBJC__DEBUG_DIR}")
            #
            unset( MULLE__OBJC__DEBUG_DEFINITIONS)
            include( "${_TMP_MULLE__OBJC__DEBUG_DIR}/Definitions.cmake" OPTIONAL)
            list( APPEND INHERITED_DEFINITIONS ${MULLE__OBJC__DEBUG_DEFINITIONS})
            break()
         else()
            message( STATUS "${_TMP_MULLE__OBJC__DEBUG_DIR} not found")
         endif()
      endforeach()
   else()
      # Enable with: `mulle-sourcetree mark mulle-objc-debug require`
      message( STATUS "MULLE__OBJC__DEBUG_LIBRARY is missing but it is marked as \"no-require\"")
   endif()
endif()
