#! /bin/sh

# with serial its easier to read the logs
# tje MULLE_FETCH_SEARCH_PATH setting is convenient for local travis tests
# with mulle-project-local-travis and the -e option
#
echo "MULLE_HOSTNAME=\"${MULLE_HOSTNAME}\"" 2>&1
echo "MULLE_FETCH_SEARCH_PATH=\"${MULLE_FETCH_SEARCH_PATH}\"" 2>&1

mulle-sde -DMULLE_FETCH_SEARCH_PATH="${MULLE_FETCH_SEARCH_PATH}" -v craft --serial || exit 1

if [ -d test ]
then
   # here verbose is more distracting and duplicates much of what we've seen
   mulle-sde -DMULLE_FETCH_SEARCH_PATH="${MULLE_FETCH_SEARCH_PATH}" test craft &&
   mulle-sde -DMULLE_FETCH_SEARCH_PATH="${MULLE_FETCH_SEARCH_PATH}" -v test run --serial
fi
