#ifndef mulle_objc_import_h__
#define mulle_objc_import_h__

/* This is a central include file to keep dependencies out of the library
   Objective-C files. It is usally imported by Objective-C .h files only.
   .m and .aam use import-private.h.
*/

/* we do this check here instead of MulleObjC.h, because then it's
   possibly to say #import "NSObject.h" in other projects if they
   use -Idependence/include/MulleObjC
 */
#ifdef MULLE_OBJC_RUNTIME_VERSION
# error "do not include the mulle-objc-runtime before MulleObjC.h"
#endif

/*
   Get C includes first
 */
#import "mulle-objc.h"

/* Include the header file automatically generated by c-sourcetree-update.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */

// #import "_MulleObjC-import.h"

/* You can add some more import statements here */


#endif
