/*
 *   This file will be regenerated by `mulle-sde reflect` and any edits will be
 *   lost. Suppress generation of this file with:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not generate any header files:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
 */

#ifndef _MulleObjC_include_h__
#define _MulleObjC_include_h__

// How to tweak the following mulle-container #include
//    remove:             `mulle-sourcetree mark mulle-container no-header`
//    rename:             `mulle-sde dependency|library set mulle-container include whatever.h`
//    toggle #import:     `mulle-sourcetree mark mulle-container [no-]import`
//    toggle localheader: `mulle-sourcetree mark mulle-container [no-]localheader`
//    toggle public:      `mulle-sourcetree mark mulle-container [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-container [no-]require`
//    remove for os:      `mulle-sourcetree mark mulle-container no-os-<osname>`
# if defined( __has_include) && __has_include("mulle-container.h")
#   include "mulle-container.h"   // mulle-container
# else
#   include <mulle-container/mulle-container.h>   // mulle-container
# endif

#endif
