/*
*   This file will be regenerated by `mulle-sde reflect` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global \
*         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _MulleObjC_import_h__
#define _MulleObjC_import_h__

/* no headers */

#ifdef __has_include
# if __has_include( "_MulleObjC-include.h")
#  include "_MulleObjC-include.h"
# endif
#endif


#endif
