/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_include_h__
#define _mulle_objc_include_h__

// You can tweak the following #include with these commands.
// (Use e2dd59c0-8e52-4deb-a014-f44435122832 instead of mulle-container if there are duplicate entries)
//    remove:             `mulle-sourcetree mark mulle-container no-header`
//    rename:             `mulle-sde dependency|library set mulle-container include whatever.h`
//    reorder:            `mulle-sourcetree move mulle-container <up|down>`
//    toggle #include:    `mulle-sourcetree mark mulle-container [no-]import`
//    toggle public:      `mulle-sourcetree mark mulle-container [no-]public`
//    toggle optional:    `mulle-sourcetree mark mulle-container [no-]require`
//    remove for platform:`mulle-sourcetree mark mulle-container no-platform-<uname>`
//        (use mulle-sourcetree-to-c --unames for known values)
#include <mulle-container/mulle-container.h>   // mulle-container

#endif
