/*
 *   This file will be regenerated by `mulle-bash`.
 *   Any edits will be lost.
 */
#if defined( MULLE_CONTAINER_VERSION)
# if MULLE_CONTAINER_VERSION < ((6 << 20) | (1 << 8) | 0)
#  error "mulle-container is too old"
# endif
# if MULLE_CONTAINER_VERSION >= ((7 << 20) | (0 << 8) | 0)
#  error "mulle-container is too new"
# endif
#endif

#if defined( MULLE_FPRINTF_VERSION)
# if MULLE_FPRINTF_VERSION < ((0 << 20) | (1 << 8) | 1)
#  error "mulle-fprintf is too old"
# endif
# if MULLE_FPRINTF_VERSION >= ((0 << 20) | (2 << 8) | 0)
#  error "mulle-fprintf is too new"
# endif
#endif

#if defined( MULLE_MULTIFIFO_VERSION)
# if MULLE_MULTIFIFO_VERSION < ((0 << 20) | (0 << 8) | 3)
#  error "mulle-multififo is too old"
# endif
# if MULLE_MULTIFIFO_VERSION >= ((0 << 20) | (1 << 8) | 0)
#  error "mulle-multififo is too new"
# endif
#endif

#if defined( MULLE_OBJC_DEBUG_VERSION)
# if MULLE_OBJC_DEBUG_VERSION < ((0 << 20) | (20 << 8) | 2)
#  error "mulle-objc-debug is too old"
# endif
# if MULLE_OBJC_DEBUG_VERSION >= ((0 << 20) | (21 << 8) | 0)
#  error "mulle-objc-debug is too new"
# endif
#endif

#if defined( MULLE_OBJC_RUNTIME_VERSION)
# if MULLE_OBJC_RUNTIME_VERSION < ((0 << 20) | (22 << 8) | 0)
#  error "mulle-objc-runtime is too old"
# endif
# if MULLE_OBJC_RUNTIME_VERSION >= ((0 << 20) | (23 << 8) | 0)
#  error "mulle-objc-runtime is too new"
# endif
#endif
