/*
 *   This file will be regenerated by `mulle-project-versioncheck`.
 *   Any edits will be lost.
 */
#if defined( MULLE_OBJC_DEBUG_VERSION)
# if MULLE_OBJC_DEBUG_VERSION < ((0 << 20) | (21 << 8) | 0)
#  error "mulle-objc-debug is too old"
# endif
# if MULLE_OBJC_DEBUG_VERSION >= ((0 << 20) | (22 << 8) | 0)
#  error "mulle-objc-debug is too new"
# endif
#endif

#if defined( MULLE_OBJC_RUNTIME_VERSION)
# if MULLE_OBJC_RUNTIME_VERSION < ((0 << 20) | (22 << 8) | 1)
#  error "mulle-objc-runtime is too old"
# endif
# if MULLE_OBJC_RUNTIME_VERSION >= ((0 << 20) | (23 << 8) | 0)
#  error "mulle-objc-runtime is too new"
# endif
#endif
