/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_include_h__
#define _mulle_objc_include_h__

// You can tweak the following #include with these commands.
// (Use e2dd59c0-8e52-4deb-a014-f44435122832 instead of mulle-container if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-container no-header`
//    rename:              `mulle-sde dependency|library set mulle-container include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-container <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-container [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-container [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-container [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-container no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-container/mulle-container.h>   // mulle-container

// You can tweak the following #include with these commands.
// (Use 35955F81-51A7-4110-961E-9411CD19E833 instead of mulle-fprintf if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-fprintf no-header`
//    rename:              `mulle-sde dependency|library set mulle-fprintf include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-fprintf <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-fprintf [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-fprintf [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-fprintf [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-fprintf no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-fprintf/mulle-fprintf.h>   // mulle-fprintf

// You can tweak the following #include with these commands.
// (Use 3CF3C024-E36E-435F-8EFD-A276D01527DF instead of mulle-multififo if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-multififo no-header`
//    rename:              `mulle-sde dependency|library set mulle-multififo include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-multififo <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-multififo [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-multififo [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-multififo [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-multififo no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-multififo/mulle-multififo.h>   // mulle-multififo

#endif
