/*
 *   This file will be regenerated by `mulle-match-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_C_HEADERS_FILE DISABLE
 *
 *   To not let mulle-match-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_MATCH_TO_C_RUN DISABLE
 */
#ifndef mulle_objc_provide_h__
#define mulle_objc_provide_h__


#include "mulle-sprintf-object.h"
#include "minimal.h"
#include "mulle-objc-classbit.h"
#include "mulle-objc-fastclassid.h"
#include "mulle-objc-fastmethodid.h"
#include "mulle-objc.h"
#include "mulle-objc-threadfoundationinfo.h"
#include "mulle-objc-type.h"


#endif
