      { @selector( MulleDynamicObject), @selector( NSMutableCopying) },      // d9918780;MulleDynamicObject;4aa86031;NSMutableCopying
      { @selector( MulleDynamicObject), MULLE_OBJC_NO_CATEGORYID },      // d9918780;MulleDynamicObject;;
      { @selector( MulleObjCClassCluster), MULLE_OBJC_NO_CATEGORYID },      // 6ed73da1;MulleObjCClassCluster;;
      { @selector( MulleObjCException), MULLE_OBJC_NO_CATEGORYID },      // a228e119;MulleObjCException;;
      { @selector( MulleObjCImmutable), MULLE_OBJC_NO_CATEGORYID },      // 8d61fecc;MulleObjCImmutable;;
      { @selector( MulleObjCPlaceboRetainCount), MULLE_OBJC_NO_CATEGORYID },      // 33c36b09;MulleObjCPlaceboRetainCount;;
      { @selector( MulleObjCRootObject), MULLE_OBJC_NO_CATEGORYID },      // 26cbaef3;MulleObjCRootObject;;
      { @selector( MulleObjCSingleton), MULLE_OBJC_NO_CATEGORYID },      // 0e51ed11;MulleObjCSingleton;;
      { @selector( MulleObjCTaggedPointer), MULLE_OBJC_NO_CATEGORYID },      // 15c9ad56;MulleObjCTaggedPointer;;
      { @selector( MulleObjCThreadSafe), MULLE_OBJC_NO_CATEGORYID },      // 8b122dd3;MulleObjCThreadSafe;;
      { @selector( MulleObjCThreadUnsafe), MULLE_OBJC_NO_CATEGORYID },      // 5414daed;MulleObjCThreadUnsafe;;
      { @selector( MulleObject), MULLE_OBJC_NO_CATEGORYID },      // a4b69f59;MulleObject;;
      { @selector( NSAutoreleasePool), MULLE_OBJC_NO_CATEGORYID },      // 58bb178a;NSAutoreleasePool;;
      { @selector( NSCondition), MULLE_OBJC_NO_CATEGORYID },      // 0397143e;NSCondition;;
      { @selector( NSConditionLock), MULLE_OBJC_NO_CATEGORYID },      // 5e0deecf;NSConditionLock;;
      { @selector( NSCopyingWithAllocator), MULLE_OBJC_NO_CATEGORYID },      // 2dc572ec;NSCopyingWithAllocator;;
      { @selector( NSInvocation), MULLE_OBJC_NO_CATEGORYID },      // c089c043;NSInvocation;;
      { @selector( NSLock), MULLE_OBJC_NO_CATEGORYID },      // cd92d31f;NSLock;;
      { @selector( NSMethodSignature), MULLE_OBJC_NO_CATEGORYID },      // 523989f9;NSMethodSignature;;
      { @selector( NSMutableCopying), MULLE_OBJC_NO_CATEGORYID },      // 4aa86031;NSMutableCopying;;
      { @selector( NSNull), MULLE_OBJC_NO_CATEGORYID },      // f0c42d79;NSNull;;
      { @selector( NSObject), @selector( NSCodingSupport) },      // b3a66256;NSObject;55df6832;NSCodingSupport
      { @selector( NSObject), @selector( NSCopying) },      // b3a66256;NSObject;903fb1df;NSCopying
      { @selector( NSObject), @selector( _NSNull) },      // b3a66256;NSObject;90d3fc87;_NSNull
      { @selector( NSObject), MULLE_OBJC_NO_CATEGORYID },      // b3a66256;NSObject;;
      { @selector( NSProxy), MULLE_OBJC_NO_CATEGORYID },      // 9a42ec29;NSProxy;;
      { @selector( NSRecursiveLock), MULLE_OBJC_NO_CATEGORYID },      // 8ffcedd9;NSRecursiveLock;;
      { @selector( NSThread), MULLE_OBJC_NO_CATEGORYID },      // c81b9c22;NSThread;;
      { @selector( _MulleObjCAutoreleaseAllocation), MULLE_OBJC_NO_CATEGORYID },      // e01ebb50;_MulleObjCAutoreleaseAllocation;;
      { @selector( _MulleObjCInstantiatePlaceholder), MULLE_OBJC_NO_CATEGORYID },      // 45dab2c5;_MulleObjCInstantiatePlaceholder;;
      { @selector( _MulleObjCLargeZombie), MULLE_OBJC_NO_CATEGORYID },      // 63fd6ba7;_MulleObjCLargeZombie;;
      { @selector( _MulleObjCZombie), MULLE_OBJC_NO_CATEGORYID },      // 3e4af9b8;_MulleObjCZombie;;
