      { @selector( MulleAutolockingObject), MULLE_OBJC_NO_CATEGORYID },      // 6eb2f41b;MulleAutolockingObject;;
      { @selector( MulleDynamicObject), MULLE_OBJC_NO_CATEGORYID },      // d9918780;MulleDynamicObject;;
      { @selector( MulleObject), MULLE_OBJC_NO_CATEGORYID },      // a4b69f59;MulleObject;;
      { @selector( MulleProxy), MULLE_OBJC_NO_CATEGORYID },      // 52ede52b;MulleProxy;;
      { @selector( NSAutoreleasePool), MULLE_OBJC_NO_CATEGORYID },      // 58bb178a;NSAutoreleasePool;;
      { @selector( NSCondition), MULLE_OBJC_NO_CATEGORYID },      // 0397143e;NSCondition;;
      { @selector( NSConditionLock), MULLE_OBJC_NO_CATEGORYID },      // 5e0deecf;NSConditionLock;;
      { @selector( NSInvocation), @selector( MulleBasicAccessors) },      // c089c043;NSInvocation;139e8b0f;MulleBasicAccessors
      { @selector( NSInvocation), MULLE_OBJC_NO_CATEGORYID },      // c089c043;NSInvocation;;
      { @selector( NSLock), MULLE_OBJC_NO_CATEGORYID },      // cd92d31f;NSLock;;
      { @selector( NSMethodSignature), @selector( NSInvocation) },      // 523989f9;NSMethodSignature;c089c043;NSInvocation
      { @selector( NSMethodSignature), MULLE_OBJC_NO_CATEGORYID },      // 523989f9;NSMethodSignature;;
      { @selector( NSMethodSignatureLoader), MULLE_OBJC_NO_CATEGORYID },      // 97e16ec5;NSMethodSignatureLoader;;
      { @selector( NSNull), MULLE_OBJC_NO_CATEGORYID },      // f0c42d79;NSNull;;
      { @selector( NSObject), @selector( NSCodingSupport) },      // b3a66256;NSObject;55df6832;NSCodingSupport
      { @selector( NSObject), @selector( _NSNull) },      // b3a66256;NSObject;90d3fc87;_NSNull
      { @selector( NSObject), @selector( _NSValue) },      // b3a66256;NSObject;8fc3f568;_NSValue
      { @selector( NSObject), MULLE_OBJC_NO_CATEGORYID },      // b3a66256;NSObject;;
      { @selector( NSProxy), MULLE_OBJC_NO_CATEGORYID },      // 9a42ec29;NSProxy;;
      { @selector( NSRecursiveLock), MULLE_OBJC_NO_CATEGORYID },      // 8ffcedd9;NSRecursiveLock;;
      { @selector( NSThread), MULLE_OBJC_NO_CATEGORYID },      // c81b9c22;NSThread;;
      { @selector( NSValue), MULLE_OBJC_NO_CATEGORYID },      // 96deaa7d;NSValue;;
      { @selector( _MulleObjCAutoreleaseAllocation), MULLE_OBJC_NO_CATEGORYID },      // e01ebb50;_MulleObjCAutoreleaseAllocation;;
      { @selector( _MulleObjCConcreteValue), MULLE_OBJC_NO_CATEGORYID },      // 7aa5a738;_MulleObjCConcreteValue;;
      { @selector( _MulleObjCInstantiatePlaceholder), MULLE_OBJC_NO_CATEGORYID },      // 45dab2c5;_MulleObjCInstantiatePlaceholder;;
      { @selector( _MulleObjCLargeZombie), MULLE_OBJC_NO_CATEGORYID },      // 63fd6ba7;_MulleObjCLargeZombie;;
      { @selector( _MulleObjCZombie), MULLE_OBJC_NO_CATEGORYID },      // 3e4af9b8;_MulleObjCZombie;;
