/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulleobjc__dependencies_h__
#define _mulleobjc__dependencies_h__

# include <mulle-container/mulle-container.h>   // mulle-container

# if ! defined( __mingw__)
#  include <dlfcn.h>   // dlfcn
# endif

# if defined( __mingw__)
#  include <psapi.h>   // psapi
# endif

#endif
