/*
* This file will be regenerated by `mulle-sde update|monitor`.
* Edits will be lost.
* Suppress this file with MULLE_SDE_IMPORT_FILENAME NONE|DISABLE.
*/

#ifndef _mulle_objc_import_h__
#define _mulle_objc_import_h__

/* no headers */

#endif
