/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulleobjc__dependencies_h__
#define _mulleobjc__dependencies_h__

# include <mulle-objc-runtime/mulle-objc-runtime.h>

# include <mulle-objc-list/mulle-objc-list.h>

# include <mulle-container/mulle-container.h>

#endif
