/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_objc_include_private_h__
#define _mulle_objc_include_private_h__

# include <mulle-objc-runtime/mulle-objc-runtime.h>   // mulle-objc-runtime

#endif
