/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulleobjc__dependencies_h__
#define _mulleobjc__dependencies_h__

# include <mulle-container/mulle-container.h>   // mulle-container

#endif
