/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
*/

#ifndef _mulle_objc_include_private_h__
#define _mulle_objc_include_private_h__

# if ! defined( _WIN32)
#  include <dlfcn.h>   // dlfcn
# endif

# if defined( _WIN32)
#  include <psapi.h>   // psapi
# endif

#endif
