/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
   Suppress this file with MULLE_SOURCETREE_TO_C_PRIVATEINCLUDE_FILE NONE|DISABLE.
*/
/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost.
   Suppress this file with MULLE_SOURCETREE_TO_C_IMPORT_FILE NONE|DISABLE.
*/
#ifndef _mulle_objc_include_private_h__
#define _mulle_objc_include_private_h__

# if defined( _WIN32)
# if __has_include(<dlfcn.h>)
#   include <dlfcn.h>   // dlfcn
# endif
# endif

# if defined( _WIN32)
# if __has_include(<psapi.h>)
#   include <psapi.h>   // psapi
# endif
# endif

# if ! defined( _WIN32)
# if __has_include(<dl.h>)
#   include <dl.h>   // dl
# endif
# endif

#endif

