/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost. Suppress this file with:

   mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*/

#ifndef _mulle_objc_import_h__
#define _mulle_objc_import_h__

/* no headers */

#endif
