/*
* This file will be regenerated by `mulle-sde update|monitor`.
* Edits will be lost.
* Suppress this file with MULLE_SDE_IMPORT_PRIVATE_FILENAME NONE|DISABLE.
*/

#ifndef _mulle_objc_import_private_h__
#define _mulle_objc_import_private_h__

/* no headers */

#endif
