#ifndef _mulleobjc_dependencies_h__
#define _mulleobjc_dependencies_h__

/* a central include file to keep dependencies out of the actual .c files
   the advantage: .c files can be moved to other projects and don't need
   to be edited. Also less typing...
*/

/* include header file automatically generated by c-sourcetree-update */
# include "_MulleObjC-dependencies.h"

/* add some more dependencies here */

#endif
