      { @selector( MulleObjCClassCluster), MULLE_OBJC_NO_CATEGORYID },      // 94ad9328;MulleObjCClassCluster;;
      { @selector( MulleObjCException), MULLE_OBJC_NO_CATEGORYID },      // f79b54ed;MulleObjCException;;
      { @selector( MulleObjCSingleton), MULLE_OBJC_NO_CATEGORYID },      // 92b74525;MulleObjCSingleton;;
      { @selector( MulleObjCTaggedPointer), MULLE_OBJC_NO_CATEGORYID },      // cd797859;MulleObjCTaggedPointer;;
      { @selector( NSAutoreleasePool), MULLE_OBJC_NO_CATEGORYID },      // 5b791fc6;NSAutoreleasePool;;
      { @selector( NSCopying), MULLE_OBJC_NO_CATEGORYID },      // ebf69c61;NSCopying;;
      { @selector( NSInvocation), MULLE_OBJC_NO_CATEGORYID },      // ad5656d2;NSInvocation;;
      { @selector( NSLock), MULLE_OBJC_NO_CATEGORYID },      // ccba22ad;NSLock;;
      { @selector( NSMethodSignature), MULLE_OBJC_NO_CATEGORYID },      // 6901a863;NSMethodSignature;;
      { @selector( NSObject), @selector( NSCodingSupport) },      // e9e78cbd;NSObject;2ce49e5f;NSCodingSupport
      { @selector( NSObject), @selector( NSCopying) },      // e9e78cbd;NSObject;ebf69c61;NSCopying
      { @selector( NSObject), MULLE_OBJC_NO_CATEGORYID },      // e9e78cbd;NSObject;;
      { @selector( NSProxy), MULLE_OBJC_NO_CATEGORYID },      // 50df5880;NSProxy;;
      { @selector( NSRecursiveLock), MULLE_OBJC_NO_CATEGORYID },      // 72108da9;NSRecursiveLock;;
      { @selector( NSThread), MULLE_OBJC_NO_CATEGORYID },      // 645eeb40;NSThread;;
      { @selector( _MulleObjCInstantiatePlaceholder), MULLE_OBJC_NO_CATEGORYID },      // 56154b76;_MulleObjCInstantiatePlaceholder;;
      { @selector( _MulleObjCLargeZombie), MULLE_OBJC_NO_CATEGORYID },      // afb92130;_MulleObjCLargeZombie;;
      { @selector( _MulleObjCZombie), MULLE_OBJC_NO_CATEGORYID },      // 057fc0af;_MulleObjCZombie;;
