      { @selector( MulleObjCClassCluster), MULLE_OBJC_NO_CATEGORYID },      // 94ad9328,00000000
      { @selector( MulleObjCException), MULLE_OBJC_NO_CATEGORYID },      // f79b54ed,00000000
      { @selector( MulleObjCSingleton), MULLE_OBJC_NO_CATEGORYID },      // 92b74525,00000000
      { @selector( MulleObjCTaggedPointer), MULLE_OBJC_NO_CATEGORYID },      // cd797859,00000000
      { @selector( NSAutoreleasePool), MULLE_OBJC_NO_CATEGORYID },      // 5b791fc6,00000000
      { @selector( NSCopying), MULLE_OBJC_NO_CATEGORYID },      // ebf69c61,00000000
      { @selector( NSInvocation), MULLE_OBJC_NO_CATEGORYID },      // ad5656d2,00000000
      { @selector( NSLock), MULLE_OBJC_NO_CATEGORYID },      // ccba22ad,00000000
      { @selector( NSMethodSignature), MULLE_OBJC_NO_CATEGORYID },      // 6901a863,00000000
      { @selector( NSObject), @selector( NSCodingSupport) },      // e9e78cbd,2ce49e5f
      { @selector( NSObject), @selector( NSCopying) },      // e9e78cbd,ebf69c61
      { @selector( NSObject), MULLE_OBJC_NO_CATEGORYID },      // e9e78cbd,00000000
      { @selector( NSProxy), MULLE_OBJC_NO_CATEGORYID },      // 50df5880,00000000
      { @selector( NSRecursiveLock), MULLE_OBJC_NO_CATEGORYID },      // 72108da9,00000000
      { @selector( NSThread), MULLE_OBJC_NO_CATEGORYID },      // 645eeb40,00000000
      { @selector( _MulleObjCInstantiatePlaceholder), MULLE_OBJC_NO_CATEGORYID },      // 56154b76,00000000
      { @selector( _MulleObjCLargeZombie), MULLE_OBJC_NO_CATEGORYID },      // afb92130,00000000
      { @selector( _MulleObjCZombie), MULLE_OBJC_NO_CATEGORYID },      // 057fc0af,00000000
