#ifndef mulle_objc_import_h__
#define mulle_objc_import_h__

/* This is a central include file to keep dependencies out of the library
   Objective-C files. It is usally imported by Objective-C .h files only.
   .m and .aam use import-private.h.
*/

/*
   Get C includes first
 */
#import "include.h"

/* Include the header file automatically generated by c-sourcetree-update.
   Here the prefix is harmless and serves disambiguation. If you have no
   sourcetree, then you don't need it.
 */

#import "_MulleObjC-import.h"

/* You can add some more import statements here */

#if MULLE_OBJC_RUNTIME_VERSION < ((0 << 20) | (14 << 8) | 0)
# error "mulle-objc-runtime is too old"
#endif

#endif
