# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/protocols
) 

set( PRIVATE_HEADERS
src/NSMethodSignature+Private.h
)

set( PUBLIC_HEADERS
src/dependencies.h
src/dependencies.inc
src/MulleObjCAllocation.h
src/MulleObjCFunctions.h
src/MulleObjC.h
src/MulleObjCLoader.h
src/_ns_autoreleasepointerarray.h
src/NSAutoreleasePool.h
src/ns_byteorder.h
src/ns_debug.h
src/NSDebug.h
src/_ns_exception.h
src/ns_exception.h
src/ns_fastclassids.h
src/ns_fastmethodids.h
src/ns_int_type.h
src/NSInvocation.h
src/NSLock.h
src/NSMethodSignature.h
src/ns_objc_compatibility.h
src/ns_objc_compiler.h
src/ns_objc.h
src/ns_objc_include.h
src/ns_objc_setup.h
src/ns_objc_startup.inc
src/ns_objc_type.h
src/NSObject.h
src/NSObject+NSCodingSupport.h
src/NSProxy.h
src/ns_range.h
src/NSRecursiveLock.h
src/ns_rootconfiguration.h
src/ns_test_allocation.h
src/ns_threadconfiguration.h
src/NSThread.h
src/ns_zone.h
src/protocols/MulleObjCClassCluster.h
src/protocols/MulleObjCException.h
src/protocols/MulleObjCRuntimeObject.h
src/protocols/MulleObjCSingleton.h
src/protocols/MulleObjCTaggedPointer.h
src/protocols/NSCoding.h
src/protocols/NSCopying.h
src/protocols/NSFastEnumeration.h
src/protocols/NSLocking.h
src/protocols/NSObjectProtocol.h
) 

