# cmake/_Headers.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

set( INCLUDE_DIRS
src
src/class
src/function
src/protocol
src/struct
) 

set( PRIVATE_HEADERS
src/class/NSMethodSignature-Private.h
src/import-private.h
src/include-private.h
src/mulle-objc-autoreleasepointerarray-private.h
src/mulle-objc-exceptionhandlertable-private.h
src/mulle-objc-rootconfiguration-private.h
src/mulle-objc-setup-private.h
src/mulle-objc-startup-private.inc
)

set( PUBLIC_HEADERS
src/MulleObjCCompiler.h
src/MulleObjCIntegralType.h
src/MulleObjC.h
src/class/MulleObjCLoader.h
src/class/NSAutoreleasePool.h
src/class/NSInvocation.h
src/class/NSLock.h
src/class/NSMethodSignature.h
src/class/NSObject+NSCodingSupport.h
src/class/NSObject.h
src/class/NSProxy.h
src/class/NSRecursiveLock.h
src/class/NSThread.h
src/function/MulleObjCAllocation.h
src/function/MulleObjCExceptionHandler.h
src/function/MulleObjCFunctions.h
src/function/MulleObjCStackFrame.h
src/function/NSByteOrder.h
src/function/NSDebug.h
src/import.h
src/include.h
src/minimal.h
src/mulle-objc-classbit.h
src/mulle-objc-fastclassid.h
src/mulle-objc-fastmethodid.h
src/mulle-objc.h
src/mulle-objc-testallocator.h
src/mulle-objc-threadconfiguration.h
src/mulle-objc-type.h
src/protocol/MulleObjCClassCluster.h
src/protocol/MulleObjCException.h
src/protocol/MulleObjCRuntimeObject.h
src/protocol/MulleObjCSingleton.h
src/protocol/MulleObjCTaggedPointer.h
src/protocol/NSCoding.h
src/protocol/NSCopying.h
src/protocol/NSFastEnumeration.h
src/protocol/NSLocking.h
src/protocol/NSObjectProtocol.h
src/struct/NSRange.h
src/struct/NSZone.h
src/version.h
) 

