#
# cmake/_Libraries.cmake is generated by `mulle-sde`. Edits will be lost.
#
if( MULLE_TRACE_INCLUDE)
   message( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

# sourcetree: DLFCN;no-all-load,no-cmakeinherit,no-import,no-load-all,no-public,no-require,only-os-mingw;
if( ${CMAKE_SYSTEM_NAME} MATCHES "Windows")
   if( NOT DLFCN_LIBRARY)
      find_library( DLFCN_LIBRARY NAMES dlfcn)
      message( STATUS "DLFCN_LIBRARY is ${DLFCN_LIBRARY}")
      #
      # the order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need
      if( DLFCN_LIBRARY)
         #
         # Add to DLFCN_LIBRARY list.
         # Disable with: `mark no-cmakeadd`
         #
         set( OS_SPECIFIC_LIBRARIES
            ${OS_SPECIFIC_LIBRARIES}
            ${DLFCN_LIBRARY}
            CACHE INTERNAL "need to cache this"
         )
         # intentionally left blank
      else()
         message( STATUS "DLFCN_LIBRARY is missing but it is marked as \"no-require\"")
      endif()
   endif()
endif()


# sourcetree: PSAPI;no-all-load,no-cmakeinherit,no-import,no-public,no-require,only-os-mingw;
if( ${CMAKE_SYSTEM_NAME} MATCHES "Windows")
   if( NOT PSAPI_LIBRARY)
      find_library( PSAPI_LIBRARY NAMES psapi)
      message( STATUS "PSAPI_LIBRARY is ${PSAPI_LIBRARY}")
      #
      # the order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need
      if( PSAPI_LIBRARY)
         #
         # Add to PSAPI_LIBRARY list.
         # Disable with: `mark no-cmakeadd`
         #
         set( OS_SPECIFIC_LIBRARIES
            ${OS_SPECIFIC_LIBRARIES}
            ${PSAPI_LIBRARY}
            CACHE INTERNAL "need to cache this"
         )
         # intentionally left blank
      else()
         message( STATUS "PSAPI_LIBRARY is missing but it is marked as \"no-require\"")
      endif()
   endif()
endif()


# sourcetree: DL;no-all-load,no-cmakeinherit,no-import,no-load-all,no-os-mingw,no-public,no-require;
if( NOT ${CMAKE_SYSTEM_NAME} MATCHES "Windows")
   if( NOT DL_LIBRARY)
      find_library( DL_LIBRARY NAMES dl)
      message( STATUS "DL_LIBRARY is ${DL_LIBRARY}")
      #
      # the order looks ascending, but due to the way this file is read
      # it ends up being descending, which is what we need
      if( DL_LIBRARY)
         #
         # Add to DL_LIBRARY list.
         # Disable with: `mark no-cmakeadd`
         #
         set( OS_SPECIFIC_LIBRARIES
            ${OS_SPECIFIC_LIBRARIES}
            ${DL_LIBRARY}
            CACHE INTERNAL "need to cache this"
         )
         # intentionally left blank
      else()
         message( STATUS "DL_LIBRARY is missing but it is marked as \"no-require\"")
      endif()
   endif()
endif()
